version: "3.3"

services:

  db:
    image: postgres:13
    ports: 
      - 127.0.0.1:5432:5432
    env_file: dipdup.env
    restart: always
    volumes:
      - db:/var/lib/postgres/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  hasura:
    image: hasura/graphql-engine:v2.0.4
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - db
    env_file: dipdup.env
    restart: always
  
volumes:
  db:
