# generated by datamodel-codegen:
#   filename:  list_token.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class ListTokenParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    price: str
    token_id: str
