# generated by datamodel-codegen:
#   filename:  mint.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class MintParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    category: str
    collection_id: str
    collection_name: str
    creator_name: str
    creator_royalty: str
    editions: str
    ipfs_hash: str
    keywords: str
    name: str
    on_sale: bool
    price: str
    symbol: str
    token_id: str
    token_metadata_uri: str
