# generated by datamodel-codegen:
#   filename:  tokens_value.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, Extra


class TokensValue(BaseModel):
    class Config:
        extra = Extra.forbid

    decimals: str
    extras: Dict[str, str]
    token_id: str
    price: str
    ipfs_hash: str
    owner: str
    on_sale: bool
    on_auction: bool
    collection_id: str
    creator: str
    creator_royalty: str
    edition_number: str
    editions: str
